---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spacy-server-deployment
spec:
  selector:
    matchLabels:
      app: utility
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
      - name: spacy-server
        image: gcr.io/questo2/spacy-server
        ports:
        - containerPort: 5556