---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: util-keyword-deployment
spec:
  selector:
    matchLabels:
      app: util
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: util
    spec:
      containers:
      - name: swisscom-keyword-extraction
        image: gcr.io/questo2/util-keyword-extraction
        ports:
        - containerPort: 5556
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
