---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gapfill-deployment
spec:
  selector:
    matchLabels:
      app: qgen
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: qgen
    spec:
      containers:
      - name: gapfill
        image: gcr.io/questo2/gapfill
        ports:
        - containerPort: 5556